FROM python:3.8

WORKDIR /app

COPY requirements.txt requirements-indirect.txt requirements-dev.txt /app/

RUN echo "Installing/upgrading pip and setuptools" && \
    pip install --upgrade pip setuptools

RUN echo "Installing Python dependencies" && \
    pip install -r requirements.txt -r requirements-indirect.txt -r requirements-dev.txt
