version: '3.8'
services:
  db:
    image: mysql:8.2.0
    cap_add:
      - SYS_NICE
    restart: always
    container_name: LetSeatDB
    environment:
      MYSQL_DATABASE: letseat
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
