FROM python:3.8

WORKDIR /app

COPY requirements.txt requirements-indirect.txt requirements-dev.txt /app/

RUN pip install --upgrade pip setuptools
RUN pip install -r requirements.txt -r requirements-indirect.txt -r requirements-dev.txt

# Add the rest of your Dockerfile as needed
