###
POST http://localhost:8010/restaurant
Content-Type: application/json

{
  "restaurantName": "Kamm's Restrant",
  "token": 11234567899009,
  "location": "Klonowicza 71A",
  "restaurantCategory": "AMERICAN"
}

<> 2023-12-07T141714.200.json
<> 2023-12-05T145746.200.json

###
GET http://localhost:8010/restaurants

<> 2023-12-05T145916.200.json
<> 2023-12-05T145358.200.json

###
PUT http://localhost:8010/updateRestaurant/10
Content-Type: application/json

{
  "restaurantName": "Kamm's Restaurant",
  "token": 11234567899009,
  "location": "Klonowicza 71A",
  "restaurantCategory": "MEXICAN"
}

###
GET http://localhost:8010/restaurant/102

<> 2023-12-07T141749.200.json
<> 2023-12-05T145944.200.json
<> 2023-12-05T145358-1.200.json

###
DELETE http://localhost:8010/deleteRestaurant/102

<> 2023-12-07T141755.200.json
<> 2023-12-05T145358-2.200.json

####################################
###
POST http://localhost:8010/menu
Content-Type: application/json

{
  "token": 11234567899009,
  "name": "Pizza",
  "price": 30.20,
  "restaurantId": 52
}

<> 2023-12-07T141806.200.json

###
GET http://localhost:8010/menu/105

<> 2023-12-07T144148.200.json
<> 2023-12-07T144046.404.json

###
PUT http://localhost:8010/updateMenu/2
Content-Type: application/json

{
  "token": 11234567899009,
  "name": "Pizza",
  "price": 30.20,
  "restaurantId": 52
}

<> 2023-12-07T144212.200.json

###
DELETE http://localhost:8010/deleteMenu/2

<> 2023-12-07T144223.200.json
################################
###
POST http://localhost:8010/table
Content-Type: application/json

{
  "token": 11234567899009,
  "restaurantId": 2,
  "twoOs": 2,
  "fourOs": 4,
  "sixOs": 6,
  "eightOs": 8
}

<> 2023-12-07T144324.200.json
<> 2023-12-07T144240.200.json

###
GET http://localhost:8010/tables

###
GET http://localhost:8010/table/1

###
PUT http://localhost:8010/updateTables/3
Content-Type: application/json

{
  "token": 11234567899009,
  "restaurantId": 2,
  "twoOs": 1,
  "fourOs": 2,
  "sixOs": 4,
  "eightOs": 7
}
###
DELETE http://localhost:8010/deleteTable/1



###
GET http://localhost:8010/menu/1

###
GET http://localhost:8010/search?latitude=23.723418&longitude=114.255942&radius=10

###
GET http://localhost:8010/restaurants

###
POST http://localhost:8010/table
Content-Type: application/json

{"restaurantId": 5,
  "token": 1520218166,
  "twoOs": 2,
  "fourOs": 4,
  "sixOs": 6,
  "eightOs": 8
}

###
DELETE http://localhost:8010/deleteTable/2

###
POST http://localhost:8010/table
Content-Type: application/json

{
  "size": 3,
  "tableId": 6,
  "restaurantId": 5,
  "token": 1520218166
}

###
GET http://localhost:8010/tables

###
GET http://localhost:8010/panel/5


###
POST http://localhost:8010/menu
Content-Type: application/json

{
  "token": 1520218166,
  "restaurantId": 5,
  "name": "Pizza",
  "price": 10.00
}


