###
POST http://localhost:8080/restaurant
Content-Type: application/json

{"restaurantId":1,"token":"5989968884","restaurantName":"Hickle-Goldner","location":"46 Mariners Cove Drive","restaurantCategory":"ITALIAN"}
###
POST http://localhost:8080/restaurant
Content-Type: application/json

{"restaurantId":2,"token":"4435615320","restaurantName":"Reilly Inc","location":"277 Commercial Hill","restaurantCategory":"CHINESE"}
###
POST http://localhost:8080/restaurant
Content-Type: application/json

{"restaurantId":3,"token":"0497179350","restaurantName":"Skiles, Sawayn and Bradtke","location":"76 Stone Corner Alley","restaurantCategory":"MEXICAN"}
###
POST http://localhost:8080/restaurant
Content-Type: application/json

{"restaurantId":4,"token":"8338317543","restaurantName":"Koss, Mohr and Hintz","location":"167 Southridge Alley","restaurantCategory":"MEXICAN"}
###
POST http://localhost:8080/restaurant
Content-Type: application/json

{"restaurantId":5,"token":"4918121810","restaurantName":"McDermott, Hintz and Leannon","location":"434 Warbler Park","restaurantCategory":"AMERICAN"}
###
POST http://localhost:8080/restaurant
Content-Type: application/json

{"restaurantId":6,"token":"8556587739","restaurantName":"Skiles, Smith and Borer","location":"39741 Esch Alley","restaurantCategory":"INDIAN"}
###
POST http://localhost:8080/restaurant
Content-Type: application/json

{"restaurantId":7,"token":"3604804515","restaurantName":"Rempel-Jones","location":"48333 Talmadge Avenue","restaurantCategory":"JAPANESE"}
###
POST http://localhost:8080/restaurant
Content-Type: application/json

{"restaurantId":8,"token":"8692548154","restaurantName":"Bruen, Wyman and Boyer","location":"68 Chinook Center","restaurantCategory":"FRENCH"}
###
POST http://localhost:8080/restaurant
Content-Type: application/json

{"restaurantId":9,"token":"0718020898","restaurantName":"Brown, Daniel and Nolan","location":"922 Westport Center","restaurantCategory":"OTHER"}
###
POST http://localhost:8080/restaurant
Content-Type: application/json

{"restaurantId":10,"token":"1962822559","restaurantName":"Hauck-Haag","location":"9904 Miller Junction","restaurantCategory":"OTHER"}