###
GET http://localhost:8010/api/reviews/restaurant/1
Content-Type: application/json

###
GET http://localhost:8010/api/reviews
Content-Type: application/json

###
GET http://localhost:8010/api/reviews/1
Content-Type: application/json


###
POST http://localhost:8010/api/reviews
Content-Type: application/json

{
  "restaurantId": 1,
  "token": "11a234v5678b99009",
  "atmosphere": 1,
  "comment": "bad",
  "food": 1,
  "service": 1
}

###
POST http://localhost:8010/api/reviews
Content-Type: application/json

{
  "restaurantId": 1,
  "token": "11a234v5678b99009",
  "atmosphere": 5,
  "comment": "weird taste",
  "food": 3,
  "service": 5
}


###
PATCH  http://localhost:8010/api/reviews/1
Authorization: "11a234v5678b99009"
Content-Type: application/json

{
  "restaurantId": 1,
  "token": "11a234v5678b99009",
  "atmosphere": 5,
  "comment": "excellent",
  "food": 5,
  "service": 5
}

###
DELETE http://localhost:8010/api/reviews/1
Authorization: "11a234v5678b99009"
