###
POST http://localhost:8010/reviews
Content-Type: application/json

###
POST http://localhost:8010/reviews
Content-Type: application/json

{
  "restaurantId": 1,
  "token": 11234567899002,
  "atmosphere": 1,
  "comment": "bad",
  "food": 1,
  "service": 1
}