###
POST http://localhost:8010/table
Content-Type: application/json

{"token": 11234567899009,"size": 2, "restaurantId": 1}

###
GET http://localhost:8010/tables

###
GET http://localhost:8010/table/2

###
PUT http://localhost:8010/updateTables/1
Content-Type: application/json

{"tableId": 1,"token": 11234567,"size": 4, "restaurantId": 1}

###
DELETE http://localhost:8010/deleteTable/1