name: Java CI with Maven, Dockerfile, and Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Step 1: Build Docker image using Dockerfile
      - name: Build Docker image
        run: docker build -t my-container .

      # Step 2: Set up Docker Compose
      - name: Set up Docker Compose
        uses: docker/compose@v1  # Use an appropriate version or tag

      # Step 3: Build and run Docker Compose
      - name: Build and run Docker Compose
        run: |
          docker-compose up -d
          docker-compose ps

      # Step 4: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 5: Build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Step 6: Optional - Uploads the full dependency graph
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6